# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eventinfo.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PButtonCancel_2(object):
    def setupUi(self, PButtonCancel_2):
        PButtonCancel_2.setObjectName("PButtonCancel_2")
        PButtonCancel_2.resize(640, 779)
        self.horizontalLayout = QtWidgets.QHBoxLayout(PButtonCancel_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.line_7 = QtWidgets.QFrame(PButtonCancel_2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.label_13 = QtWidgets.QLabel(PButtonCancel_2)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(PButtonCancel_2)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Text_EventName = QtWidgets.QPlainTextEdit(PButtonCancel_2)
        self.Text_EventName.setMaximumSize(QtCore.QSize(400, 30))
        self.Text_EventName.setObjectName("Text_EventName")
        self.verticalLayout_2.addWidget(self.Text_EventName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Text_TrackLength = QtWidgets.QPlainTextEdit(PButtonCancel_2)
        self.Text_TrackLength.setMaximumSize(QtCore.QSize(100, 30))
        self.Text_TrackLength.setObjectName("Text_TrackLength")
        self.verticalLayout_2.addWidget(self.Text_TrackLength)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.calendarWidget = QtWidgets.QCalendarWidget(PButtonCancel_2)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_3.addWidget(self.calendarWidget)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.label_3 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.line_6 = QtWidgets.QFrame(PButtonCancel_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.rButtonDownhill = QtWidgets.QRadioButton(PButtonCancel_2)
        self.rButtonDownhill.setObjectName("rButtonDownhill")
        self.buttonGroup = QtWidgets.QButtonGroup(PButtonCancel_2)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rButtonDownhill)
        self.horizontalLayout_2.addWidget(self.rButtonDownhill)
        self.RbuttonSDownhill = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RbuttonSDownhill.setObjectName("RbuttonSDownhill")
        self.buttonGroup.addButton(self.RbuttonSDownhill)
        self.horizontalLayout_2.addWidget(self.RbuttonSDownhill)
        self.RButtonFlat = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonFlat.setObjectName("RButtonFlat")
        self.buttonGroup.addButton(self.RButtonFlat)
        self.horizontalLayout_2.addWidget(self.RButtonFlat)
        self.RButtonSUphill = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonSUphill.setObjectName("RButtonSUphill")
        self.buttonGroup.addButton(self.RButtonSUphill)
        self.horizontalLayout_2.addWidget(self.RButtonSUphill)
        self.rButtonUphill = QtWidgets.QRadioButton(PButtonCancel_2)
        self.rButtonUphill.setObjectName("rButtonUphill")
        self.buttonGroup.addButton(self.rButtonUphill)
        self.horizontalLayout_2.addWidget(self.rButtonUphill)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_9 = QtWidgets.QLabel(PButtonCancel_2)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_4 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(PButtonCancel_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rButtonFlat = QtWidgets.QRadioButton(PButtonCancel_2)
        self.rButtonFlat.setObjectName("rButtonFlat")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(PButtonCancel_2)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.rButtonFlat)
        self.horizontalLayout_3.addWidget(self.rButtonFlat)
        self.RButtonSUneven = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonSUneven.setObjectName("RButtonSUneven")
        self.buttonGroup_2.addButton(self.RButtonSUneven)
        self.horizontalLayout_3.addWidget(self.RButtonSUneven)
        self.rButtonVUneven = QtWidgets.QRadioButton(PButtonCancel_2)
        self.rButtonVUneven.setObjectName("rButtonVUneven")
        self.buttonGroup_2.addButton(self.rButtonVUneven)
        self.horizontalLayout_3.addWidget(self.rButtonVUneven)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_10 = QtWidgets.QLabel(PButtonCancel_2)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.label_5 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.line_2 = QtWidgets.QFrame(PButtonCancel_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RButtonShort = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonShort.setObjectName("RButtonShort")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(PButtonCancel_2)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.RButtonShort)
        self.horizontalLayout_4.addWidget(self.RButtonShort)
        self.RButtonMedium = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonMedium.setObjectName("RButtonMedium")
        self.buttonGroup_3.addButton(self.RButtonMedium)
        self.horizontalLayout_4.addWidget(self.RButtonMedium)
        self.RButtonLong = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonLong.setObjectName("RButtonLong")
        self.buttonGroup_3.addButton(self.RButtonLong)
        self.horizontalLayout_4.addWidget(self.RButtonLong)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_11 = QtWidgets.QLabel(PButtonCancel_2)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.label_6 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.line_8 = QtWidgets.QFrame(PButtonCancel_2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout.addWidget(self.line_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.RButtonDry = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonDry.setObjectName("RButtonDry")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(PButtonCancel_2)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.RButtonDry)
        self.horizontalLayout_5.addWidget(self.RButtonDry)
        self.RButtonLightRain = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonLightRain.setObjectName("RButtonLightRain")
        self.buttonGroup_4.addButton(self.RButtonLightRain)
        self.horizontalLayout_5.addWidget(self.RButtonLightRain)
        self.RButtonHeavyRain = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonHeavyRain.setObjectName("RButtonHeavyRain")
        self.buttonGroup_4.addButton(self.RButtonHeavyRain)
        self.horizontalLayout_5.addWidget(self.RButtonHeavyRain)
        self.RButtonSnow = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonSnow.setObjectName("RButtonSnow")
        self.buttonGroup_4.addButton(self.RButtonSnow)
        self.horizontalLayout_5.addWidget(self.RButtonSnow)
        self.RButtonHail = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonHail.setObjectName("RButtonHail")
        self.buttonGroup_4.addButton(self.RButtonHail)
        self.horizontalLayout_5.addWidget(self.RButtonHail)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_12 = QtWidgets.QLabel(PButtonCancel_2)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.label_7 = QtWidgets.QLabel(PButtonCancel_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.line_9 = QtWidgets.QFrame(PButtonCancel_2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout.addWidget(self.line_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.RButtonFreezing = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonFreezing.setObjectName("RButtonFreezing")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(PButtonCancel_2)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.RButtonFreezing)
        self.horizontalLayout_6.addWidget(self.RButtonFreezing)
        self.RButtonCold = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonCold.setObjectName("RButtonCold")
        self.buttonGroup_5.addButton(self.RButtonCold)
        self.horizontalLayout_6.addWidget(self.RButtonCold)
        self.RButtonMild = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonMild.setObjectName("RButtonMild")
        self.buttonGroup_5.addButton(self.RButtonMild)
        self.horizontalLayout_6.addWidget(self.RButtonMild)
        self.RButtonWarm = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonWarm.setObjectName("RButtonWarm")
        self.buttonGroup_5.addButton(self.RButtonWarm)
        self.horizontalLayout_6.addWidget(self.RButtonWarm)
        self.RButtonHot = QtWidgets.QRadioButton(PButtonCancel_2)
        self.RButtonHot.setObjectName("RButtonHot")
        self.buttonGroup_5.addButton(self.RButtonHot)
        self.horizontalLayout_6.addWidget(self.RButtonHot)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem12)
        self.PButtonCancel = QtWidgets.QPushButton(PButtonCancel_2)
        self.PButtonCancel.setObjectName("PButtonCancel")
        self.horizontalLayout_7.addWidget(self.PButtonCancel)
        self.pushButton = QtWidgets.QPushButton(PButtonCancel_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(PButtonCancel_2)
        QtCore.QMetaObject.connectSlotsByName(PButtonCancel_2)

    def retranslateUi(self, PButtonCancel_2):
        _translate = QtCore.QCoreApplication.translate
        PButtonCancel_2.setWindowTitle(_translate("PButtonCancel_2", "Event Information"))
        self.label_8.setText(_translate("PButtonCancel_2", "Event Information"))
        self.label.setText(_translate("PButtonCancel_2", "Event Name"))
        self.label_2.setText(_translate("PButtonCancel_2", "Track Length (metres)"))
        self.label_14.setText(_translate("PButtonCancel_2", "Event Date"))
        self.label_3.setText(_translate("PButtonCancel_2", "Incline"))
        self.rButtonDownhill.setText(_translate("PButtonCancel_2", "Downhill"))
        self.RbuttonSDownhill.setText(_translate("PButtonCancel_2", "Slightly Downhill"))
        self.RButtonFlat.setText(_translate("PButtonCancel_2", "Flat"))
        self.RButtonSUphill.setText(_translate("PButtonCancel_2", "Slightly Uphill"))
        self.rButtonUphill.setText(_translate("PButtonCancel_2", "Uphill"))
        self.label_4.setText(_translate("PButtonCancel_2", "Track Condition"))
        self.rButtonFlat.setText(_translate("PButtonCancel_2", "Flat"))
        self.RButtonSUneven.setText(_translate("PButtonCancel_2", "Slightly Uneven"))
        self.rButtonVUneven.setText(_translate("PButtonCancel_2", "Very Uneven"))
        self.label_5.setText(_translate("PButtonCancel_2", "Grass Length"))
        self.RButtonShort.setText(_translate("PButtonCancel_2", "Short"))
        self.RButtonMedium.setText(_translate("PButtonCancel_2", "Medium"))
        self.RButtonLong.setText(_translate("PButtonCancel_2", "Long"))
        self.label_6.setText(_translate("PButtonCancel_2", "Precipitation"))
        self.RButtonDry.setText(_translate("PButtonCancel_2", "Dry"))
        self.RButtonLightRain.setText(_translate("PButtonCancel_2", "Light Rain"))
        self.RButtonHeavyRain.setText(_translate("PButtonCancel_2", "Heavy Rain"))
        self.RButtonSnow.setText(_translate("PButtonCancel_2", "Snow"))
        self.RButtonHail.setText(_translate("PButtonCancel_2", "Hailstones"))
        self.label_7.setText(_translate("PButtonCancel_2", "Temperature"))
        self.RButtonFreezing.setText(_translate("PButtonCancel_2", "Freezing"))
        self.RButtonCold.setText(_translate("PButtonCancel_2", "Cold"))
        self.RButtonMild.setText(_translate("PButtonCancel_2", "Mild"))
        self.RButtonWarm.setText(_translate("PButtonCancel_2", "Warm"))
        self.RButtonHot.setText(_translate("PButtonCancel_2", "Hot"))
        self.PButtonCancel.setText(_translate("PButtonCancel_2", "Cancel"))
        self.pushButton.setText(_translate("PButtonCancel_2", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PButtonCancel_2 = QtWidgets.QWidget()
    ui = Ui_PButtonCancel_2()
    ui.setupUi(PButtonCancel_2)
    PButtonCancel_2.show()
    sys.exit(app.exec_())

