# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eventinfo.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EventInformation(object):
    def setupUi(self, EventInformation):
        EventInformation.setObjectName("EventInformation")
        EventInformation.resize(640, 480)
        self.horizontalLayout = QtWidgets.QHBoxLayout(EventInformation)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(EventInformation)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(EventInformation)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.line = QtWidgets.QFrame(EventInformation)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(EventInformation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(EventInformation)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(100, 30))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.verticalLayout.addWidget(self.plainTextEdit_2)
        self.line_6 = QtWidgets.QFrame(EventInformation)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.label_3 = QtWidgets.QLabel(EventInformation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_5 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup = QtWidgets.QButtonGroup(EventInformation)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_5)
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_4 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.horizontalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_3 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(EventInformation)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(EventInformation)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_4 = QtWidgets.QLabel(EventInformation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_8 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(EventInformation)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_8)
        self.horizontalLayout_3.addWidget(self.radioButton_8)
        self.radioButton_7 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup_2.addButton(self.radioButton_7)
        self.horizontalLayout_3.addWidget(self.radioButton_7)
        self.radioButton_6 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_2.addButton(self.radioButton_6)
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(EventInformation)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.label_5 = QtWidgets.QLabel(EventInformation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_10 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_10.setObjectName("radioButton_10")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(EventInformation)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioButton_10)
        self.horizontalLayout_4.addWidget(self.radioButton_10)
        self.radioButton_9 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup_3.addButton(self.radioButton_9)
        self.horizontalLayout_4.addWidget(self.radioButton_9)
        self.radioButton_11 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_11.setObjectName("radioButton_11")
        self.buttonGroup_3.addButton(self.radioButton_11)
        self.horizontalLayout_4.addWidget(self.radioButton_11)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_4 = QtWidgets.QFrame(EventInformation)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.label_6 = QtWidgets.QLabel(EventInformation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_16 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_16.setObjectName("radioButton_16")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(EventInformation)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.radioButton_16)
        self.horizontalLayout_5.addWidget(self.radioButton_16)
        self.radioButton_15 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_15.setObjectName("radioButton_15")
        self.buttonGroup_4.addButton(self.radioButton_15)
        self.horizontalLayout_5.addWidget(self.radioButton_15)
        self.radioButton_23 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_23.setObjectName("radioButton_23")
        self.buttonGroup_4.addButton(self.radioButton_23)
        self.horizontalLayout_5.addWidget(self.radioButton_23)
        self.radioButton_22 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_22.setObjectName("radioButton_22")
        self.buttonGroup_4.addButton(self.radioButton_22)
        self.horizontalLayout_5.addWidget(self.radioButton_22)
        self.radioButton_14 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_14.setObjectName("radioButton_14")
        self.buttonGroup_4.addButton(self.radioButton_14)
        self.horizontalLayout_5.addWidget(self.radioButton_14)
        self.radioButton_13 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_13.setObjectName("radioButton_13")
        self.buttonGroup_4.addButton(self.radioButton_13)
        self.horizontalLayout_5.addWidget(self.radioButton_13)
        self.radioButton_12 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_12.setObjectName("radioButton_12")
        self.buttonGroup_4.addButton(self.radioButton_12)
        self.horizontalLayout_5.addWidget(self.radioButton_12)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.line_5 = QtWidgets.QFrame(EventInformation)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.label_7 = QtWidgets.QLabel(EventInformation)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_21 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_21.setObjectName("radioButton_21")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(EventInformation)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.radioButton_21)
        self.horizontalLayout_6.addWidget(self.radioButton_21)
        self.radioButton_20 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_20.setObjectName("radioButton_20")
        self.buttonGroup_5.addButton(self.radioButton_20)
        self.horizontalLayout_6.addWidget(self.radioButton_20)
        self.radioButton_19 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_19.setObjectName("radioButton_19")
        self.buttonGroup_5.addButton(self.radioButton_19)
        self.horizontalLayout_6.addWidget(self.radioButton_19)
        self.radioButton_18 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_18.setObjectName("radioButton_18")
        self.buttonGroup_5.addButton(self.radioButton_18)
        self.horizontalLayout_6.addWidget(self.radioButton_18)
        self.radioButton_17 = QtWidgets.QRadioButton(EventInformation)
        self.radioButton_17.setObjectName("radioButton_17")
        self.buttonGroup_5.addButton(self.radioButton_17)
        self.horizontalLayout_6.addWidget(self.radioButton_17)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(EventInformation)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(EventInformation)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label.raise_()

        self.retranslateUi(EventInformation)
        QtCore.QMetaObject.connectSlotsByName(EventInformation)

    def retranslateUi(self, EventInformation):
        _translate = QtCore.QCoreApplication.translate
        EventInformation.setWindowTitle(_translate("EventInformation", "Event Information"))
        self.label.setText(_translate("EventInformation", "Event Name"))
        self.label_2.setText(_translate("EventInformation", "Track Length (metres)"))
        self.label_3.setText(_translate("EventInformation", "Incline"))
        self.radioButton_5.setText(_translate("EventInformation", "Downhill"))
        self.radioButton_4.setText(_translate("EventInformation", "Slightly Downhill"))
        self.radioButton_3.setText(_translate("EventInformation", "Flat"))
        self.radioButton_2.setText(_translate("EventInformation", "Slightly Uphill"))
        self.radioButton.setText(_translate("EventInformation", "Uphill"))
        self.label_4.setText(_translate("EventInformation", "Track Condition"))
        self.radioButton_8.setText(_translate("EventInformation", "Flat"))
        self.radioButton_7.setText(_translate("EventInformation", "Slightly Uneven"))
        self.radioButton_6.setText(_translate("EventInformation", "Very Uneven"))
        self.label_5.setText(_translate("EventInformation", "Grass Length"))
        self.radioButton_10.setText(_translate("EventInformation", "Short"))
        self.radioButton_9.setText(_translate("EventInformation", "Medium"))
        self.radioButton_11.setText(_translate("EventInformation", "Long"))
        self.label_6.setText(_translate("EventInformation", "Precipitation"))
        self.radioButton_16.setText(_translate("EventInformation", "Dry"))
        self.radioButton_15.setText(_translate("EventInformation", "Light Rain"))
        self.radioButton_23.setText(_translate("EventInformation", "Dry"))
        self.radioButton_22.setText(_translate("EventInformation", "Light Rain"))
        self.radioButton_14.setText(_translate("EventInformation", "Heavy Rain"))
        self.radioButton_13.setText(_translate("EventInformation", "Snow"))
        self.radioButton_12.setText(_translate("EventInformation", "Hailstones"))
        self.label_7.setText(_translate("EventInformation", "Temperature"))
        self.radioButton_21.setText(_translate("EventInformation", "Freezing"))
        self.radioButton_20.setText(_translate("EventInformation", "Cold"))
        self.radioButton_19.setText(_translate("EventInformation", "Mild"))
        self.radioButton_18.setText(_translate("EventInformation", "Warm"))
        self.radioButton_17.setText(_translate("EventInformation", "Hot"))
        self.pushButton_2.setText(_translate("EventInformation", "Cancel"))
        self.pushButton.setText(_translate("EventInformation", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EventInformation = QtWidgets.QWidget()
    ui = Ui_EventInformation()
    ui.setupUi(EventInformation)
    EventInformation.show()
    sys.exit(app.exec_())

