# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1175, 870)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pButton_eventInfo = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_eventInfo.setObjectName("pButton_eventInfo")
        self.verticalLayout_3.addWidget(self.pButton_eventInfo)
        self.plainTextEdit_16 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_16.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.plainTextEdit_16.setFont(font)
        self.plainTextEdit_16.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_16.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_16.setObjectName("plainTextEdit_16")
        self.verticalLayout_3.addWidget(self.plainTextEdit_16)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.pButton_NewDog = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_NewDog.setObjectName("pButton_NewDog")
        self.verticalLayout_3.addWidget(self.pButton_NewDog)
        self.pButton_EditDeleteDog = QtWidgets.QPushButton(self.centralwidget)
        self.pButton_EditDeleteDog.setObjectName("pButton_EditDeleteDog")
        self.verticalLayout_3.addWidget(self.pButton_EditDeleteDog)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_29.addWidget(self.label_19)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem2)
        self.Text_LatestTime = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_LatestTime.sizePolicy().hasHeightForWidth())
        self.Text_LatestTime.setSizePolicy(sizePolicy)
        self.Text_LatestTime.setMinimumSize(QtCore.QSize(40, 0))
        self.Text_LatestTime.setMaximumSize(QtCore.QSize(120, 45))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_LatestTime.setFont(font)
        self.Text_LatestTime.setAcceptDrops(True)
        self.Text_LatestTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_LatestTime.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_LatestTime.setObjectName("Text_LatestTime")
        self.horizontalLayout_28.addWidget(self.Text_LatestTime)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_28)
        self.pButton_SaveTime = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_SaveTime.sizePolicy().hasHeightForWidth())
        self.pButton_SaveTime.setSizePolicy(sizePolicy)
        self.pButton_SaveTime.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pButton_SaveTime.setObjectName("pButton_SaveTime")
        self.verticalLayout_3.addWidget(self.pButton_SaveTime)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Text_OwnerDogName = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_OwnerDogName.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_OwnerDogName.setFont(font)
        self.Text_OwnerDogName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_OwnerDogName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_OwnerDogName.setObjectName("Text_OwnerDogName")
        self.horizontalLayout_13.addWidget(self.Text_OwnerDogName)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_13.addWidget(self.line_12)
        self.Text_OverUnder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_OverUnder.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_OverUnder.setFont(font)
        self.Text_OverUnder.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_OverUnder.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_OverUnder.setObjectName("Text_OverUnder")
        self.horizontalLayout_13.addWidget(self.Text_OverUnder)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Text_Time1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_Time1.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_Time1.setFont(font)
        self.Text_Time1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_Time1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_Time1.setObjectName("Text_Time1")
        self.verticalLayout_7.addWidget(self.Text_Time1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_4.addWidget(self.line_5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Text_Time2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_Time2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_Time2.setFont(font)
        self.Text_Time2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_Time2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_Time2.setObjectName("Text_Time2")
        self.verticalLayout_8.addWidget(self.Text_Time2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.Text_GroupAB = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_GroupAB.sizePolicy().hasHeightForWidth())
        self.Text_GroupAB.setSizePolicy(sizePolicy)
        self.Text_GroupAB.setMaximumSize(QtCore.QSize(50, 100))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_GroupAB.setFont(font)
        self.Text_GroupAB.setObjectName("Text_GroupAB")
        self.horizontalLayout_15.addWidget(self.Text_GroupAB)
        self.pButton_PreviousDog = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_PreviousDog.sizePolicy().hasHeightForWidth())
        self.pButton_PreviousDog.setSizePolicy(sizePolicy)
        self.pButton_PreviousDog.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pButton_PreviousDog.setIconSize(QtCore.QSize(24, 24))
        self.pButton_PreviousDog.setObjectName("pButton_PreviousDog")
        self.horizontalLayout_15.addWidget(self.pButton_PreviousDog)
        self.pButton_NextDog = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pButton_NextDog.sizePolicy().hasHeightForWidth())
        self.pButton_NextDog.setSizePolicy(sizePolicy)
        self.pButton_NextDog.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pButton_NextDog.setObjectName("pButton_NextDog")
        self.horizontalLayout_15.addWidget(self.pButton_NextDog)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_26.addWidget(self.label_18)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_26.addWidget(self.label_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.Text_FirstGPAUnder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_FirstGPAUnder.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_FirstGPAUnder.setPalette(palette)
        self.Text_FirstGPAUnder.setObjectName("Text_FirstGPAUnder")
        self.horizontalLayout_27.addWidget(self.Text_FirstGPAUnder)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_27.addWidget(self.line_9)
        self.Text_FirstGPAOver = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_FirstGPAOver.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_FirstGPAOver.setPalette(palette)
        self.Text_FirstGPAOver.setObjectName("Text_FirstGPAOver")
        self.horizontalLayout_27.addWidget(self.Text_FirstGPAOver)
        self.verticalLayout_3.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_24.addWidget(self.label_16)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_24.addWidget(self.label_15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.Text_SecondGPAUnder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_SecondGPAUnder.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_SecondGPAUnder.setPalette(palette)
        self.Text_SecondGPAUnder.setObjectName("Text_SecondGPAUnder")
        self.horizontalLayout_25.addWidget(self.Text_SecondGPAUnder)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_25.addWidget(self.line_8)
        self.Text_SecondGPAOver = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_SecondGPAOver.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_SecondGPAOver.setPalette(palette)
        self.Text_SecondGPAOver.setObjectName("Text_SecondGPAOver")
        self.horizontalLayout_25.addWidget(self.Text_SecondGPAOver)
        self.verticalLayout_3.addLayout(self.horizontalLayout_25)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Text_FirstGPBUnder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_FirstGPBUnder.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_FirstGPBUnder.setPalette(palette)
        self.Text_FirstGPBUnder.setObjectName("Text_FirstGPBUnder")
        self.horizontalLayout_7.addWidget(self.Text_FirstGPBUnder)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_7.addWidget(self.line_11)
        self.Text_FirstGPBOver = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_FirstGPBOver.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_FirstGPBOver.setPalette(palette)
        self.Text_FirstGPBOver.setObjectName("Text_FirstGPBOver")
        self.horizontalLayout_7.addWidget(self.Text_FirstGPBOver)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_10.addWidget(self.label_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Text_SecondGPBUnder = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_SecondGPBUnder.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_SecondGPBUnder.setPalette(palette)
        self.Text_SecondGPBUnder.setObjectName("Text_SecondGPBUnder")
        self.horizontalLayout_11.addWidget(self.Text_SecondGPBUnder)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_11.addWidget(self.line_6)
        self.Text_SecondGPBOver = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Text_SecondGPBOver.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(123, 123, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.Text_SecondGPBOver.setPalette(palette)
        self.Text_SecondGPBOver.setObjectName("Text_SecondGPBOver")
        self.horizontalLayout_11.addWidget(self.Text_SecondGPBOver)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_3.addWidget(self.line_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Text_FastestTime = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_FastestTime.sizePolicy().hasHeightForWidth())
        self.Text_FastestTime.setSizePolicy(sizePolicy)
        self.Text_FastestTime.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Text_FastestTime.setFont(font)
        self.Text_FastestTime.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_FastestTime.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Text_FastestTime.setObjectName("Text_FastestTime")
        self.horizontalLayout_9.addWidget(self.Text_FastestTime)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dogList = QtWidgets.QColumnView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dogList.sizePolicy().hasHeightForWidth())
        self.dogList.setSizePolicy(sizePolicy)
        self.dogList.setMinimumSize(QtCore.QSize(0, 0))
        self.dogList.setObjectName("dogList")
        self.verticalLayout.addWidget(self.dogList)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Text_previousTimeRecorded = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_previousTimeRecorded.sizePolicy().hasHeightForWidth())
        self.Text_previousTimeRecorded.setSizePolicy(sizePolicy)
        self.Text_previousTimeRecorded.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Text_previousTimeRecorded.setObjectName("Text_previousTimeRecorded")
        self.verticalLayout_2.addWidget(self.Text_previousTimeRecorded)
        self.Text_messagesFromSerial = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text_messagesFromSerial.sizePolicy().hasHeightForWidth())
        self.Text_messagesFromSerial.setSizePolicy(sizePolicy)
        self.Text_messagesFromSerial.setObjectName("Text_messagesFromSerial")
        self.verticalLayout_2.addWidget(self.Text_messagesFromSerial)
        self.plainTextEdit_18 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_18.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit_18.setObjectName("plainTextEdit_18")
        self.verticalLayout_2.addWidget(self.plainTextEdit_18)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.LureCrazyICO = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LureCrazyICO.sizePolicy().hasHeightForWidth())
        self.LureCrazyICO.setSizePolicy(sizePolicy)
        self.LureCrazyICO.setText("")
        self.LureCrazyICO.setPixmap(QtGui.QPixmap("LC.jpg"))
        self.LureCrazyICO.setObjectName("LureCrazyICO")
        self.horizontalLayout.addWidget(self.LureCrazyICO)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1175, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew_Event = QtWidgets.QAction(MainWindow)
        self.actionNew_Event.setObjectName("actionNew_Event")
        self.actionOpen_Even = QtWidgets.QAction(MainWindow)
        self.actionOpen_Even.setObjectName("actionOpen_Even")
        self.actionSave_Event_as = QtWidgets.QAction(MainWindow)
        self.actionSave_Event_as.setObjectName("actionSave_Event_as")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHow_to = QtWidgets.QAction(MainWindow)
        self.actionHow_to.setObjectName("actionHow_to")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExport_Times = QtWidgets.QAction(MainWindow)
        self.actionExport_Times.setObjectName("actionExport_Times")
        self.actionNew_Event_2 = QtWidgets.QAction(MainWindow)
        self.actionNew_Event_2.setObjectName("actionNew_Event_2")
        self.actionOpen_Event = QtWidgets.QAction(MainWindow)
        self.actionOpen_Event.setObjectName("actionOpen_Event")
        self.actionExport_Event_to_File = QtWidgets.QAction(MainWindow)
        self.actionExport_Event_to_File.setObjectName("actionExport_Event_to_File")
        self.actionUpload_Event_to_LureCrazy_co_uk = QtWidgets.QAction(MainWindow)
        self.actionUpload_Event_to_LureCrazy_co_uk.setObjectName("actionUpload_Event_to_LureCrazy_co_uk")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionSelect_COM_Port = QtWidgets.QAction(MainWindow)
        self.actionSelect_COM_Port.setObjectName("actionSelect_COM_Port")
        self.menuFile.addAction(self.actionNew_Event_2)
        self.menuFile.addAction(self.actionOpen_Event)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Event_to_File)
        self.menuFile.addAction(self.actionUpload_Event_to_LureCrazy_co_uk)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSelect_COM_Port)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit_2)
        self.menuHelp.addAction(self.actionHow_to)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LC Dog Timing"))
        self.pButton_eventInfo.setText(_translate("MainWindow", "Event Information"))
        self.pButton_NewDog.setText(_translate("MainWindow", "New Dog"))
        self.pButton_EditDeleteDog.setText(_translate("MainWindow", "Edit/Delete Dog"))
        self.label_19.setText(_translate("MainWindow", "Latest time recorded:"))
        self.pButton_SaveTime.setText(_translate("MainWindow", "Save time to current Dog"))
        self.label_12.setText(_translate("MainWindow", "Name"))
        self.label_11.setText(_translate("MainWindow", "Over 23\"/Under 23\""))
        self.label_5.setText(_translate("MainWindow", "Time 1:"))
        self.label_4.setText(_translate("MainWindow", "Time 2:"))
        self.label_14.setText(_translate("MainWindow", "Current group:"))
        self.pButton_PreviousDog.setText(_translate("MainWindow", "Previous Dog"))
        self.pButton_NextDog.setText(_translate("MainWindow", "Next Dog"))
        self.label_18.setText(_translate("MainWindow", "First Group A Under 23\""))
        self.label_17.setText(_translate("MainWindow", "First Group A Over 23\""))
        self.label_16.setText(_translate("MainWindow", "Second Group A Under 23\""))
        self.label_15.setText(_translate("MainWindow", "Second Group A Over 23\""))
        self.label_7.setText(_translate("MainWindow", "First Group B Under 23\""))
        self.label_6.setText(_translate("MainWindow", "First Group B Over 23\""))
        self.label_10.setText(_translate("MainWindow", "Second Group B Under 23\""))
        self.label_9.setText(_translate("MainWindow", "Second Group B Over 23\""))
        self.label_8.setText(_translate("MainWindow", "Fastest Time of the Day by:"))
        self.label.setText(_translate("MainWindow", "Dog List"))
        self.label_2.setText(_translate("MainWindow", "Previous Time Recorded"))
        self.Text_messagesFromSerial.setText(_translate("MainWindow", "Messages"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Event.setText(_translate("MainWindow", "New Event..."))
        self.actionOpen_Even.setText(_translate("MainWindow", "Open Event..."))
        self.actionSave_Event_as.setText(_translate("MainWindow", "Save Event as..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionHow_to.setText(_translate("MainWindow", "LC Dog Timing Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExport_Times.setText(_translate("MainWindow", "Export Times..."))
        self.actionNew_Event_2.setText(_translate("MainWindow", "New Event..."))
        self.actionOpen_Event.setText(_translate("MainWindow", "Open Event..."))
        self.actionExport_Event_to_File.setText(_translate("MainWindow", "Export Event to File..."))
        self.actionUpload_Event_to_LureCrazy_co_uk.setText(_translate("MainWindow", "Upload Event to LureCrazy.co.uk..."))
        self.actionExit_2.setText(_translate("MainWindow", "Exit"))
        self.actionSelect_COM_Port.setText(_translate("MainWindow", "Select COM Port..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

