# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ownerdog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_verticalLayout1(object):
    def setupUi(self, verticalLayout1):
        verticalLayout1.setObjectName("verticalLayout1")
        verticalLayout1.resize(773, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(verticalLayout1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(verticalLayout1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.line_2 = QtWidgets.QFrame(verticalLayout1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(verticalLayout1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(verticalLayout1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(verticalLayout1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(verticalLayout1)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_3.addWidget(self.plainTextEdit)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(verticalLayout1)
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.horizontalLayout_3.addWidget(self.plainTextEdit_3)
        self.pushButton_5 = QtWidgets.QPushButton(verticalLayout1)
        self.pushButton_5.setMaximumSize(QtCore.QSize(120, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_4 = QtWidgets.QPushButton(verticalLayout1)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-Expand Arrow Filled-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_9.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.line_4 = QtWidgets.QFrame(verticalLayout1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        self.label_5 = QtWidgets.QLabel(verticalLayout1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.tableView = QtWidgets.QTableView(verticalLayout1)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(verticalLayout1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(verticalLayout1)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.horizontalLayout_4.addWidget(self.plainTextEdit_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_2 = QtWidgets.QRadioButton(verticalLayout1)
        self.radioButton_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_8.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(verticalLayout1)
        self.radioButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_8.addWidget(self.radioButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.pushButton_3 = QtWidgets.QPushButton(verticalLayout1)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.line_3 = QtWidgets.QFrame(verticalLayout1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_4.addWidget(self.line_3)
        self.label_4 = QtWidgets.QLabel(verticalLayout1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.tableView_2 = QtWidgets.QTableView(verticalLayout1)
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_4.addWidget(self.tableView_2)
        self.label = QtWidgets.QLabel(verticalLayout1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(verticalLayout1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(verticalLayout1)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(verticalLayout1)
        QtCore.QMetaObject.connectSlotsByName(verticalLayout1)

    def retranslateUi(self, verticalLayout1):
        _translate = QtCore.QCoreApplication.translate
        verticalLayout1.setWindowTitle(_translate("verticalLayout1", "Form"))
        self.label_2.setText(_translate("verticalLayout1", "Search/Add owner/Dog"))
        self.label_3.setText(_translate("verticalLayout1", "Search for owner below first, if they\'re not in the database, click \"Add Owner to database\" to create a new owner."))
        self.label_7.setText(_translate("verticalLayout1", "Once a new owner has been added, make sure they\'re selected, then add their dogs."))
        self.plainTextEdit.setPlainText(_translate("verticalLayout1", "First name...\n"
""))
        self.plainTextEdit_3.setPlainText(_translate("verticalLayout1", "Surname..."))
        self.pushButton_5.setText(_translate("verticalLayout1", "Search Database"))
        self.pushButton_4.setText(_translate("verticalLayout1", "Add Owner to Database"))
        self.label_5.setText(_translate("verticalLayout1", "Owners in database"))
        self.plainTextEdit_2.setPlainText(_translate("verticalLayout1", "Add new dogs to selected owner here..."))
        self.radioButton_2.setText(_translate("verticalLayout1", "Under 23\""))
        self.radioButton.setText(_translate("verticalLayout1", "Over 23\""))
        self.pushButton_3.setText(_translate("verticalLayout1", "Add dog to selected owner"))
        self.label_4.setText(_translate("verticalLayout1", "Selected Owner\'s dogs"))
        self.label.setText(_translate("verticalLayout1", "Hold CTRL while clicking to select multiple dogs"))
        self.pushButton_2.setText(_translate("verticalLayout1", "Cancel"))
        self.pushButton.setText(_translate("verticalLayout1", "Add selected dogs to Current Event"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    verticalLayout1 = QtWidgets.QWidget()
    ui = Ui_verticalLayout1()
    ui.setupUi(verticalLayout1)
    verticalLayout1.show()
    sys.exit(app.exec_())

