# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ownerdog.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_verticalLayout1(object):
    def setupUi(self, verticalLayout1):
        verticalLayout1.setObjectName("verticalLayout1")
        verticalLayout1.resize(773, 700)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(verticalLayout1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(verticalLayout1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(verticalLayout1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(verticalLayout1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_6 = QtWidgets.QLabel(verticalLayout1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(verticalLayout1)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(verticalLayout1)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_5 = QtWidgets.QLabel(verticalLayout1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(verticalLayout1)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(verticalLayout1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.Text_OwnerName = QtWidgets.QPlainTextEdit(verticalLayout1)
        self.Text_OwnerName.setMaximumSize(QtCore.QSize(400, 30))
        self.Text_OwnerName.setObjectName("Text_OwnerName")
        self.verticalLayout_4.addWidget(self.Text_OwnerName)
        self.pushButton_2 = QtWidgets.QPushButton(verticalLayout1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(verticalLayout1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.Text_DogName = QtWidgets.QPlainTextEdit(verticalLayout1)
        self.Text_DogName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Text_DogName.setObjectName("Text_DogName")
        self.verticalLayout_7.addWidget(self.Text_DogName)
        self.pushButton = QtWidgets.QPushButton(verticalLayout1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_7.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton = QtWidgets.QRadioButton(verticalLayout1)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(verticalLayout1)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout_3.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(verticalLayout1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout_3.addWidget(self.radioButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.Database_table = QtWidgets.QTableView(verticalLayout1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Database_table.sizePolicy().hasHeightForWidth())
        self.Database_table.setSizePolicy(sizePolicy)
        self.Database_table.setMinimumSize(QtCore.QSize(0, 300))
        self.Database_table.setObjectName("Database_table")
        self.verticalLayout_2.addWidget(self.Database_table)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pButton_cancel = QtWidgets.QPushButton(verticalLayout1)
        self.pButton_cancel.setObjectName("pButton_cancel")
        self.horizontalLayout_3.addWidget(self.pButton_cancel)
        self.pButton_addToEvent = QtWidgets.QPushButton(verticalLayout1)
        self.pButton_addToEvent.setObjectName("pButton_addToEvent")
        self.horizontalLayout_3.addWidget(self.pButton_addToEvent)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.retranslateUi(verticalLayout1)
        QtCore.QMetaObject.connectSlotsByName(verticalLayout1)

    def retranslateUi(self, verticalLayout1):
        _translate = QtCore.QCoreApplication.translate
        verticalLayout1.setWindowTitle(_translate("verticalLayout1", "Form"))
        self.label.setText(_translate("verticalLayout1", "Add Owner/Dog"))
        self.label_2.setText(_translate("verticalLayout1", "Search for the owner and or dog in the boxes below, previously added/raced dogs will appear in the table below."))
        self.label_6.setText(_translate("verticalLayout1", "If the owner/dog does not appear in the table, enter details fully and add to the database."))
        self.label_7.setText(_translate("verticalLayout1", "Retrieve from database is used to edit owners and dogs; click add after edit to update databse."))
        self.label_9.setText(_translate("verticalLayout1", " "))
        self.label_5.setText(_translate("verticalLayout1", "Once dogs have been added to the database,  select them in the table (use CTRL for multiple selections) and press"))
        self.label_8.setText(_translate("verticalLayout1", "\"Add Owner/Dog To Current Event\" to add them to today\'s race."))
        self.label_3.setText(_translate("verticalLayout1", "Owner Name"))
        self.pushButton_2.setText(_translate("verticalLayout1", "Add Owner/Dog to Database \\/"))
        self.label_4.setText(_translate("verticalLayout1", "Dog Name"))
        self.pushButton.setText(_translate("verticalLayout1", "Retrieve Owner/Dog from Database /\\"))
        self.radioButton.setText(_translate("verticalLayout1", "Over"))
        self.radioButton_2.setText(_translate("verticalLayout1", "Under"))
        self.pButton_cancel.setText(_translate("verticalLayout1", "Cancel"))
        self.pButton_addToEvent.setText(_translate("verticalLayout1", "Add Owner/Dog To Current Event"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    verticalLayout1 = QtWidgets.QWidget()
    ui = Ui_verticalLayout1()
    ui.setupUi(verticalLayout1)
    verticalLayout1.show()
    sys.exit(app.exec_())

